server:
  port: 7788

spring:
  application:
    name: lobby
#  session:
#    store-type: hash_map
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${spring.application.name}?currentSchema=${spring.application.name}&stringtype=unspecified
    username: lobby
    password: password
  flyway:
    url: jdbc:postgresql://localhost:5432/${spring.application.name}
    schemas: ${spring.application.name}
    locations: classpath:db/migration,classpath:db/data
    check-location: true
    user: lobby
    password: password
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true



logging:
  level:
    org:
      springframework: info
management:
  websocket:
    trace-inbound: true
    trace-outbound: false


chat:
  max-profanity-level: 5
  disallowed-words: damn, crap, ass
  destinations.login: /chat.login
  chat.destinations.logout: /chat.logout